### PR TITLE
MCKIN-21507 fixed an incorrect attribute

### PR DESCRIPTION
**Pull request by mudassir-hafeez**
**Description:** Fixed an incorrect attribute which was throwing an exception on New Relic. 

**JIRA:** https://edx-wiki.atlassian.net/browse/MCKIN-21507
https://openedx.atlassian.net/browse/YONK-1741

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
@mudassir-hafeez As I just mentioned on YONK-1741, I think that it may need to be `.update_or_create(group=group, defaults={"invalidated_at": timezone.now()})`

Otherwise, this will raise more errors - because the model defines `group` as unique.

**Comment by mudassir-hafeez** [comment]
@bradenmacdonald thank you for reviewing it. Can you please review it once again?

**Comment by bradenmacdonald** [comment]
@mudassir-hafeez I don't have enough context to sign off on this and I'm not able to test it now so @xitij2000 will review it for you soon.

**Comment by xitij2000** [comment]
@mudassir-hafeez  Could you also add some tests? I will have a look at this soon.

**Comment by xitij2000** [comment]
@mudassir-hafeez There is another bug here: https://github.com/open-craft/openedx-completion-aggregator/blob/master/completion_aggregator/cachegroup.py#L84
It should be `invalidate*d*_at__lt` instead of `invalidate_at__lt`

**Pull request merged**
